version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x

  
  pre_build: 
    commands:
    - chmod +x install-terraform.sh configure-named-profile.sh apply-terraform.sh
    #terraform installation
    - ./install-terraform.sh
    
    #configure profile
    - ./configure-named-profile.sh

  build:
    commands:
      - ./apply-terraform.sh